export const REGISTER_LOADING = 'REGISTER_LOADING'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'
export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_LOADING = 'LOGIN_LOADING'
export const LOGOUT = 'LOGOUT'

export const GET_CONTACT_LOADING = 'GET_CONTACT_LOADING'
export const GET_CONTACT_SUCCESS = 'GET_CONTACT_SUCCESS'
export const GET_CONTACT_FAILED = 'GET_CONTACT_FAILED'

export const CREATE_CONTACT_LOADING = 'CREATE_CONTACT_LOADING'
export const CREATE_CONTACT_SUCCESS = 'CREATE_CONTACT_SUCCESS'
export const CREATE_CONTACT_FAILED = 'CREATE_CONTACT_FAILED'